dist: bionic
os: linux
language: generic

jobs:
  include:
    services:
    - mongodb
    script:
    # Issue with spaces after the colon below
    - echo -e '\nreplication:\n  replSetName:rs0' | sudo tee -a /etc/mongod.conf
    - cat /etc/mongod.conf
    - sudo systemctl restart mongod
    - sleep 10
    - sudo systemctl status mongod
    - mongo --eval 'rs.initiate()'
    - sudo cat /var/log/mongodb/mongod.log
