dist: bionic
os: linux
language: generic

jobs:
  include:
    services:
    - mongodb
    script:
    - cat /etc/mongod.conf
    - cat /etc/mongodb/mongod.conf
    - cat /var/log/mongodb/mongod.log
    - cat /var/log/syslog
