dist: bionic
os: linux
language: generic

jobs:
  include:
    services:
    - mongodb
    script:
    - |
      echo -e '\nreplication:\n  replSetName: rs0' | sudo tee -a /etc/mongod.conf &&
      sudo systemctl restart mongod &&
      mongo --eval 'rs.initiate()'
